### ISSUE TITLE
Like operator query not working?

### ISSUE THREAD

**Issue by abrarazeem** [view-components/eloquent-data-processing#1]
when using "like" operator filtering not working as it need to be.
i think problem is with value of "like" query does not adding  % sign e.g  "%value%"

**Comment by Nayjest** [comment]
Hi Abrar!
Yes, FilterOperationProcessor does not add "%" character automatically like it's done in nayjest/grids package.

I removed this feature because it's semantically not good.

Probably it would be better to add following operations
- FilterOperation::STR_STARTS_FROM 
- FilterOperation::STR_ENDS_WITH
- FilterOperation::STR_CONTAINS
  This operations will use SQL LIKE for db-based data-providers and add "%" character to appropriate place in value.
  How do you like it? Do you have any suggestions?

If you like idea of mentioned operations and want to contribute, I will be glad to accept pull-requests to view-components/viewcomponents & viewcomponents/eloquent-data-providers with implementation of mentioned operations from you, in this case please let me know that you work on this feature.

Tomorrow I will check comments here and if I will not find any news from you, I will implement it on my own.

Thanks for submitting issue!

**Comment by abrarazeem** [comment]
Yes its good idea to have these three operations rather than one "like"
I will create a fork and implement your suggestion
Actually i am using this package with mongodb. It has no issue until now. 
I will try to implement this as soon as possible than create pull request

**Comment by Nayjest** [comment]
Ok, thanks

**Comment by Nayjest** [comment]
Hi Abrar!
How are thing going?
Are you still planning to implement new operations? If not, please, give me know and I will implement it on my own.

**Comment by abrarazeem** [comment]
I have made a change to support three operations
FilterOperation::STR_STARTS_FROM
FilterOperation::STR_ENDS_WITH
FilterOperation::STR_CONTAINS

but that is just basic if else in filter process class on the basis of FilterOperation
what i really like is to class should have single responsibility, we should implement interfaces for different kind of operations, it will also cover our future needs, but for that we have change lot of classes in current system

if you want me to share current workaround i am happy to, and also if you have any other idea of doing let me know i will change mine according to that and let you know

**Comment by Nayjest** [comment]
"if - else" inside FilterProcessor is absolutely ok,  I will fix code-style and add tests anyway, so please just make pull-request with your changes (actually 2 pull requests, one with FilterOperation constants into view-components/view-components repository and second with FilterProcessor class here).

I will add this operations support to another FilterProcessor implementations later.

Regarding interfaces for different operations:
If you mean different classes for processing things like FilterOperation::STR_STARTS_FROM / FilterOperation::STR_ENDS_WITH I'm afraid, it may look overcomplicated. 

If you mean different interfaces for processing FilterOperation, SortOperation, etc  (Use FilterProcessorInterface, SortProcessorInterface, PaginateProcessorInterface instead of ProcessorInterface), I thought about it and planning to implement it, becouse currently its done not in best way (classes that implements ProcessorInterface actually can't process any objects implementing OperationInterface as it described  in `public function process($src, OperationInterface $operation);` but concrete implementations)

**Comment by Nayjest** [comment]
Added issue https://github.com/view-components/view-components/issues/26 (separate interfaces for data-provider operation processors)
